Add components markup.
better-notes/better-notes-web-client pull request #1
Opened 2020-12-07 17:08 UTC by LnSxx

2020-12-11 14:51 UTC, WinterCitizen requested changes

2020-12-11 14:51 UTC, WinterCitizen commented on src/index.js
> +reportWebVitals();
Убери, пожалуйста, вызов `reportWebVitals` и импорт.

2020-12-11 14:52 UTC, WinterCitizen commented on src/index.js
> +reportWebVitals();
И проверь что всё это нормально поднимается.

2020-12-15 18:02 UTC, WinterCitizen approved these changes
Удаление пакета не критично, если хочешь поправь и тыкай мердж.

2020-12-15 18:02 UTC, DaniilDaedalus commented on package.json
> +    "web-vitals": "^0.2.4"
Убери веб вайталс, раз уж мы от них избавились :thinking:

2020-12-17 10:39 UTC, Anon731 approved these changes
@LnSxx пры мержатся теми, кто их открывал, после аппрува

2020-12-17 10:45 UTC, LnSxx commented
> @LnSxx пры мержатся теми, кто их открывал, после аппрува

Знаю, просто я хотел еще немного подправить маркап. Сейчас.

2020-12-17 10:45 UTC, merged