Redux installation
better-notes/better-notes-web-client pull request #2
Opened 2020-12-26 17:13 UTC by LnSxx

Add redux store, actions and rootReducer.

2021-01-14 21:07 UTC, WinterCitizen requested changes

2021-01-14 21:07 UTC, DaniilDaedalus commented on src/App.jsx
> +});
Почему ты используешь мапы стейта и диспатчей вместо хуков?

2021-01-14 21:07 UTC, DaniilDaedalus commented on src/Components/Header/Header.jsx
> +          <input className="Input" type="text" disabled placeholder="Search" />
Почему все классы начинаются с маленькой буквы, а этот с большой?

2021-01-14 21:07 UTC, DaniilDaedalus commented on src/Components/Note/Note.jsx
> +      key={note.created_at}
Почему ты используешь `note.created_at` как ключ, а не `note.id_`? `created_at` не гарантирует уникальность.

2021-01-14 21:07 UTC, DaniilDaedalus commented on src/Components/Note/Note.jsx
> +    <Tag tag={tag} key={tag.name + Math.random()} />
У нас не должно быть двух одинаковых тегов у ноута. Почему бы не использовать как ключ только `tag.name`?

2021-01-14 21:07 UTC, DaniilDaedalus commented on src/Components/Note/Note.jsx
> +        ) : <div className="tagTitle">{note.text}</div>}
Почему класс для ноута называется `tagTitle`?

2021-01-14 21:07 UTC, DaniilDaedalus commented on src/Components/NoteList/NoteList.jsx
> +    <Note note={note} key={note.id_} />
Не понял. А почему `key` указывается и здесь и в компоненте Note, на 34 строке? И почему здесь он `note.id_`, а там `note.created_at`?

2021-01-14 21:07 UTC, DaniilDaedalus commented on src/Components/Tag/Tag.jsx
> +      {tag.name}
Думаю было бы читаемее иметь их на одной строке.

2021-01-14 21:07 UTC, DaniilDaedalus commented on src/Components/TagInput/TagInput.jsx
>  function TagInput() {
Почему компонент называется `TagInput`, если создаёт ноуты?

2021-01-14 21:07 UTC, WinterCitizen commented on src/api-interaction/createNote.js
> +      const response = await axios.post('http://localhost:8000/api/v1/note/create/', [request]);
`http://localhost:8000` надо вынести в какой-нибудь settings.js и получать их из энвайронмента как, например, тут - https://www.pluralsight.com/guides/how-to-store-and-read-configuration-files-using-react#module-usingenvfile. Что-нибудь в стиле

```javascript
const API_URL = env.process.REACT_APP_API_URL
const API_NOTE_CREATE_URL = `${API_URL}/api/v1/note/create/`
```

и т.д.

2021-01-14 21:07 UTC, WinterCitizen commented on src/api-interaction/createNote.js
> +    const request = { text: noteText, tags: [] };
Это не реквест, это ноут.

2021-01-14 21:07 UTC, WinterCitizen commented on src/api-interaction/fetchNotes.js
> +      const response = await axios.get('http://localhost:8000/api/v1/note/read/?limit=100&offset=0');
Лимит в 100 сломает всё как только ты обновишь бэкенд. Он должен будет быть меньше или равен двадцати. И лучше бы тебе сразу вынести `limit` и `offset` в аргументы `fetchNotes`

2021-01-15 13:59 UTC, Anon731 approved these changes

2021-01-15 13:59 UTC, Anon731 commented on src/Components/Note/Note.sass
> +    position: relative
![image](https://user-images.githubusercontent.com/30243929/104734434-4cf4a100-5751-11eb-842d-cdbe16bcddf4.png)

2021-01-15 13:59 UTC, Anon731 commented on src/api-interaction/createNote.js
> +    const request = { text: noteText, tags: [] };
Вернее это payload запроса. Request тоже валидно, но обычно request называют какой-то умный объект с кучей логики, в котором лежат данные, а тут только сами данные

2021-02-08 21:39 UTC, LnSxx commented on src/App.jsx
> +});
Мапы стейта и диспатчей убраны во всех компонентах.

2021-02-08 21:51 UTC, LnSxx commented on src/Components/Header/Header.jsx
> +          <input className="Input" type="text" disabled placeholder="Search" />
Наименование класса формы поиска изменено на "searchInput".

2021-02-08 22:13 UTC, LnSxx commented on src/Components/Note/Note.jsx
> +      key={note.created_at}
Для заметок использован ключ `note.id_`.

2021-02-08 22:16 UTC, LnSxx commented on src/Components/Note/Note.jsx
> +    <Tag tag={tag} key={tag.name + Math.random()} />
На сегодняшний денб наименования тегов не уникальны. `Math.random()` убран. Поставлена задача на обеспечение уникальности наименований тегов для каждой заметки.
https://github.com/better-notes/better-notes-web-client/issues/3

2021-02-08 22:24 UTC, LnSxx commented on src/Components/Note/Note.jsx
> +        ) : <div className="tagTitle">{note.text}</div>}
Атрибут `className` для компонента ноута переименован на `noteText`.

2021-02-08 22:30 UTC, LnSxx commented on src/Components/Tag/Tag.jsx
> +      {tag.name}
Форматирование для этой части кода производит перенос каждого из этих выражений на отдельную строку.

2021-02-09 18:54 UTC, LnSxx commented on src/Components/TagInput/TagInput.jsx
>  function TagInput() {
Название компонента (а также директории, и CSS файлов) переименовано на `NoteInput` в соответствии с выполняемой функцией.

2021-02-09 19:42 UTC, LnSxx commented on src/api-interaction/createNote.js
> +      const response = await axios.post('http://localhost:8000/api/v1/note/create/', [request]);
`http://localhost:8000` вынесен в файл .env
Необходимые ссылки запросов сформированы в новом файле `settings.js`

2021-02-09 19:45 UTC, LnSxx commented on src/api-interaction/fetchNotes.js
> +      const response = await axios.get('http://localhost:8000/api/v1/note/read/?limit=100&offset=0');
Функция `fetchNotes` переименована в `readNotes` в соответсвии с выполняемой задачей. 
Так же `limit` и `offset` функция получает в качестве аргументов, значения по умолчанию которым установлены 20 и 0 соответственно.

2021-02-09 19:56 UTC, LnSxx commented on src/api-interaction/createNote.js
> +    const request = { text: noteText, tags: [] };
`request` переименовано на `noteContent`.

2021-02-15 19:53 UTC, WinterCitizen approved these changes

2021-02-15 19:53 UTC, merged